### ISSUE TITLE
[Error] listen EACCES: permission denied 

### ISSUE THREAD

**Issue by Dragonizedpizza** [TannerReynolds/ShareX-Upload-Server#63]
```  |> [11:20:54 AM] | Error: listen EACCES: permission denied ```
What does this mean?

**Comment by radiohazard-dev** [comment]
Ah, Node errors: cryptic as can be. `permission denied` means it doesn't have permissions, and `listen` seems to suggest that it doesn't have permission to run the server on a certain port.

Typically, ports 80 and 443 (anything under 1024) are ports that require administrator permission to run, at least on Linux. On Linux, you'll need to run with sudo, and on Windows you'll need an elevated prompt. Otherwise, you can also change the ports to something higher, which won't need those permissions.

If you do that last thing, you'll just need to add `:port` to the end of the domain when using ShareX. Instead of `example.com/upload`, you'll use `example.com:port/upload`.

**Comment by Dragonizedpizza** [comment]
Cool. Thanks!
